platform :ios, '5.1.1'

pod 'DTCoreText', '~> 1.6.12'
pod 'TouchJSON', '~> 1.1'
pod 'ASIHTTPRequest', '~> 1.8.2'
pod 'CocoaAsyncSocket', '~> 7.3.5'
pod 'FMDB', '~> 2.3'
pod 'Reachability', '~> 3.1.1'
pod 'ZipArchive', '~> 1.2.0'
pod 'UIDevice-Hardware', '~> 0.1.3'
pod 'NSData+Base64', '~> 1.0.0'
pod 'ZBarSDK', '~> 1.3.1'
pod 'GZIP', '~> 1.0.2'
pod 'OpenSSL-Universal', '~> 1.0.1.h'
pod 'lua51',:git=>"https://github.com/HydraFramework/lua51.git"
pod 'curl',:git=>"https://github.com/HydraFramework/HydraDependencyCURL.git"
pod 'Box2D',:git=>"https://github.com/HydraFramework/HydraDependencyBox2D.git"
pod 'sqlcipher',:git=>"https://github.com/HydraFramework/HydraDependencySqlCipher.git"

pod 'Hydra',:git=>"https://github.com/HydraFramework/release-ios.git"
