platform :ios, '6.0.0'

# #run on new env guides.
# pod repo remove master
# pod repo add master http://git.luafan.com/Specs.git
# pod install
# #search project, add static before base64_encode, "unsigned static base64_encode"

pod 'DTCoreText', '~> 1.6.12'
pod 'TouchJSON', '~> 1.1'
pod 'ASIHTTPRequest', '~> 1.8.2'
pod 'CocoaAsyncSocket', '~> 7.3.5'
pod 'FMDB/common', '~> 2.3'
pod 'Reachability', '~> 3.1.1'
pod 'ZipArchive', '~> 1.2.0'
pod 'UIDevice-Hardware', '~> 0.1.3'
pod 'NSData+Base64', '~> 1.0.0'
pod 'ZBarSDK', '~> 1.3.1'
pod 'GZIP', '~> 1.0.2'
pod 'AnimatedGIFImageSerialization', '~> 0.2.0'

pod 'lua51',:git=>"http://git.luafan.com/lua51.git"
pod 'Box2D',:git=>"http://git.luafan.com/HydraDependencyBox2D.git"
pod 'event-ssl-curl',:git=>"http://git.luafan.com/libevent-openssl-tor-libcurl.git"

#pod 'Hydra',:git=>"http://git.luafan.com/release-ios.git"
